name: Run Minitests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15.7-bullseye
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: nsl
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: test_db
        options: >-
          --health-cmd="pg_isready -U nsl"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          
    env:
      DATABASE_URL: postgres://nsl:testpassword@localhost:5432/test_db
      RAILS_ENV: test
      EDITOR_CONFIGDB_FILE: ".nsl-test-configs/database.yml"
      EDITOR_CONFIG_FILE: ".nsl-test-configs/editor-config.rb"
      DB: test_db
      DB_USER: nsl
      DB_PASS: testpassword

    strategy:
      matrix:
        # Set N number of parallel jobs you want to run tests on.
        # Use higher number if you have slow tests to split them on more parallel jobs.
        # Remember to update ci_node_index below to 0..N-1
        ci_node_total: [2]
        # set N-1 indexes for parallel jobs
        # When you run 2 parallel jobs then first job will have index 0,
        # the second job will have index 1 etc
        ci_node_index: [0, 1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.5'

    - name: Install dependencies
      run: |
        bundle install

    - name: Set up the database
      run: |
        bin/rails db:schema:load

    - name: Run Minit Tests
      run: |
        bundle exec rails test

    - name: Run RSpec tests
      run: |
        bundle exec rspec --profile 10 --format progress --no-color --backtrace
